export enum StateActions {
  ADD_TODO = 'ADD_TODO',
  UPDATE_TODO = 'UPDATE_TODO',
  DELETE_TODO = 'DELETE_TODO',
  USERS_LOADING = 'USERS_LOADING',
  USERS_LOAIDNG_SUCCESS = 'USERS_LOAIDNG_SUCCESS',
  USERS_LOADING_FAILED = 'USERS_LOADING_FAILED',
}

export enum Screens {
  MENU = 'MENU',
  TODO_LIST = 'TODO_LIST',
  ADD_TODO = 'ADD_TODO',
  RANDOM_USER = 'RANDOM_USER',
}
